"""equipements neuf a vendre + reparation nom/marque

Revision ID: 320d855d5ad4
Revises: 9c7da91b27c3
Create Date: 2026-08-05 13:16:58.322304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '320d855d5ad4'
down_revision: Union[str, None] = '9c7da91b27c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipements_neuf_a_vendre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_serie', sa.String(length=100), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('marque', sa.String(length=150), nullable=False),
    sa.Column('type_equipement', sa.String(length=150), nullable=False),
    sa.Column('prix', sa.Float(), nullable=True),
    sa.Column('quantite_disponible', sa.Integer(), nullable=False),
    sa.Column('statut', sa.Enum('disponible', 'reserve', 'vendu', name='statut_vente'), nullable=False),
    sa.Column('date_reception', sa.Date(), nullable=False),
    sa.Column('fournisseur', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipements_neuf_a_vendre_numero_serie'), 'equipements_neuf_a_vendre', ['numero_serie'], unique=True)

    # nom_equipement -> nom : renommage (préserve les données), pas un drop+add — corrigé
    # à la main, l'autogenerate d'Alembic ne détecte pas les renommages.
    with op.batch_alter_table('equipements_attente_reparation') as batch_op:
        batch_op.alter_column('nom_equipement', new_column_name='nom', existing_type=sa.String(length=255))
        # server_default temporaire pour satisfaire NOT NULL sur d'éventuelles lignes existantes,
        # retiré juste après — le modèle ORM n'a pas de défaut pour ce champ.
        batch_op.add_column(sa.Column('marque', sa.String(length=150), nullable=False, server_default=''))
    with op.batch_alter_table('equipements_attente_reparation') as batch_op:
        batch_op.alter_column('marque', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipements_attente_reparation') as batch_op:
        batch_op.drop_column('marque')
        batch_op.alter_column('nom', new_column_name='nom_equipement', existing_type=sa.String(length=255))
    op.drop_index(op.f('ix_equipements_neuf_a_vendre_numero_serie'), table_name='equipements_neuf_a_vendre')
    op.drop_table('equipements_neuf_a_vendre')
    # ### end Alembic commands ###
