"""historique dates workflow intervention

Revision ID: 3b1ac7a49f8f
Revises: f083e97f6e53
Create Date: 2026-08-09 18:26:24.177405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b1ac7a49f8f'
down_revision: Union[str, None] = 'f083e97f6e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interventions', sa.Column('date_diagnostic', sa.DateTime(timezone=True), nullable=True))
    op.add_column('interventions', sa.Column('date_pieces_identifiees', sa.DateTime(timezone=True), nullable=True))
    op.add_column('interventions', sa.Column('date_travail_demarre', sa.DateTime(timezone=True), nullable=True))
    op.add_column('interventions', sa.Column('date_terminee', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interventions', 'date_terminee')
    op.drop_column('interventions', 'date_travail_demarre')
    op.drop_column('interventions', 'date_pieces_identifiees')
    op.drop_column('interventions', 'date_diagnostic')
    # ### end Alembic commands ###
