"""notifications ciblees par destinataire

Revision ID: 85199e3feae7
Revises: 1f117f911d7b
Create Date: 2026-08-18 18:13:51.774061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85199e3feae7'
down_revision: Union[str, None] = '1f117f911d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('destinataire_id', sa.Integer(), nullable=False),
    # 'appel_offre_detecte' ajouté rétroactivement à cette définition le 2026-09-24 (migration
    # Postgres/Supabase) — valeur Python ajoutée bien plus tard (session 47, veille marchés
    # publics) mais jamais reflétée en DDL sur cet enum ; sans impact sur SQLite (déjà appliqué,
    # VARCHAR sans contrainte), nécessaire sur Postgres où `type_notification` est un vrai type
    # ENUM natif. Voir SUIVI_PROJET.md.
    sa.Column('type', sa.Enum('intervention_assignee', 'devis_accepte', 'devis_refuse', 'pret_pour_devis', 'intervention_terminee', 'intervention_reportee', 'appel_offre_detecte', name='type_notification'), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('intervention_id', sa.String(length=20), nullable=True),
    sa.Column('lu_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['destinataire_id'], ['techniciens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    op.drop_table('notifications')
