"""initial schema with stock module

Revision ID: 9c7da91b27c3
Revises:
Create Date: 2026-08-04 20:00:31.589128

NOTE (2026-09-24, migration Postgres/Supabase) : la définition de l'enum `type_intervention`
ci-dessous a été corrigée rétroactivement — valeurs 'Curatif'/'Préventif'/'Installation'/
'Formation' d'origine remplacées par leur forme snake_case finale + 'restitution' (ajoutée
bien plus tard, jamais reflétée en DDL sur cet enum, voir migration e500f49432a4). Sans réel
impact sur SQLite (colonne VARCHAR sans contrainte, cette migration y est déjà appliquée et ne
sera pas rejouée) : correction nécessaire uniquement parce que sur Postgres `sa.Enum(...)` crée
un vrai type ENUM natif, et qu'`ALTER TYPE ... ADD VALUE` ne peut pas être utilisé dans la même
transaction que celle qui l'ajoute — inapplicable ici puisqu'`alembic upgrade head` sur une
base neuve exécute tout l'historique dans une seule transaction (voir env.py). Voir aussi la
migration b9361b4e91f8 (neutralisée sur Postgres, devenue sans objet) et SUIVI_PROJET.md.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c7da91b27c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evenements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_heure', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('type', sa.Enum('alerte', 'rapport', 'planif', 'ok', 'stock', name='type_evenement'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pieces_detachees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('type_equipement_compatible', sa.String(length=150), nullable=False),
    sa.Column('quantite_stock', sa.Integer(), nullable=False),
    sa.Column('seuil_alerte', sa.Integer(), nullable=False),
    sa.Column('fournisseur', sa.String(length=255), nullable=False),
    sa.Column('prix_unitaire', sa.Float(), nullable=True),
    sa.Column('emplacement_stock', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pieces_detachees_reference'), 'pieces_detachees', ['reference'], unique=True)
    op.create_table('techniciens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'chef_equipe', 'technicien', name='role_technicien'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('derniere_connexion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('initiales', sa.String(length=4), nullable=False),
    sa.Column('specialite', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=50), nullable=False),
    sa.Column('statut', sa.Enum('disponible', 'en_intervention', 'hors_ligne', name='statut_technicien'), nullable=False),
    sa.Column('heures_ce_mois', sa.Float(), nullable=False),
    sa.Column('objectif_heures', sa.Float(), nullable=False),
    sa.Column('interventions_ce_mois', sa.Integer(), nullable=False),
    sa.Column('note', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_techniciens_email'), 'techniciens', ['email'], unique=True)
    op.create_table('conversation_participants',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('technicien_id', sa.Integer(), nullable=False),
    sa.Column('date_ajout', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['technicien_id'], ['techniciens.id'], ),
    sa.PrimaryKeyConstraint('conversation_id', 'technicien_id')
    )
    op.create_table('equipements',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('marque', sa.String(length=150), nullable=False),
    sa.Column('localisation', sa.String(length=255), nullable=False),
    sa.Column('statut', sa.Enum('operationnel', 'en_maintenance', 'en_panne', 'maintenance_retard', name='statut_equipement'), nullable=False),
    sa.Column('niveau_alerte', sa.Enum('ok', 'warning', 'critique', name='niveau_alerte'), nullable=False),
    sa.Column('derniere_maintenance', sa.Date(), nullable=True),
    sa.Column('prochaine_maintenance', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('technicien_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['technicien_id'], ['techniciens.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipements_attente_reparation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_serie', sa.String(length=100), nullable=False),
    sa.Column('nom_equipement', sa.String(length=255), nullable=False),
    sa.Column('type_equipement', sa.String(length=150), nullable=False),
    sa.Column('etablissement_origine', sa.String(length=255), nullable=False),
    sa.Column('date_reception', sa.Date(), nullable=False),
    sa.Column('statut', sa.Enum('en_attente_diagnostic', 'en_reparation', 'en_attente_piece', 'repare', 'retourne_client', name='statut_reparation'), nullable=False),
    sa.Column('description_panne', sa.Text(), nullable=True),
    sa.Column('piece_necessaire_id', sa.Integer(), nullable=True),
    sa.Column('technicien_assigne_id', sa.Integer(), nullable=True),
    sa.Column('date_retour_prevue', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['piece_necessaire_id'], ['pieces_detachees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['technicien_assigne_id'], ['techniciens.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipements_attente_reparation_numero_serie'), 'equipements_attente_reparation', ['numero_serie'], unique=True)
    op.create_table('formations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('technicien_id', sa.Integer(), nullable=False),
    sa.Column('intitule', sa.String(length=255), nullable=False),
    sa.Column('organisme', sa.String(length=255), nullable=True),
    sa.Column('equipement_type', sa.String(length=100), nullable=True),
    sa.Column('date_obtention', sa.Date(), nullable=False),
    sa.Column('date_expiration', sa.Date(), nullable=True),
    sa.Column('statut', sa.Enum('valide', 'expiree', 'a_renouveler', name='statut_formation'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['technicien_id'], ['techniciens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('expediteur_id', sa.Integer(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('envoye_le', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('lu_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['expediteur_id'], ['techniciens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interventions',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('date_heure', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lieu', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('curatif', 'preventif', 'installation', 'formation', 'restitution', name='type_intervention'), nullable=False),
    sa.Column('statut', sa.Enum('planifie', 'en_cours', 'termine', name='statut_intervention'), nullable=False),
    sa.Column('duree_estimee', sa.Integer(), nullable=True),
    sa.Column('duree_reelle', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('technicien_id', sa.Integer(), nullable=False),
    sa.Column('equipement_id', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['equipement_id'], ['equipements.id'], ),
    sa.ForeignKeyConstraint(['technicien_id'], ['techniciens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plannings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipement_id', sa.String(length=20), nullable=False),
    sa.Column('technicien_id', sa.Integer(), nullable=True),
    sa.Column('type_intervention', sa.Enum('curatif', 'preventif', 'installation', 'formation', 'restitution', name='type_intervention'), nullable=False),
    sa.Column('frequence', sa.Enum('mensuelle', 'trimestrielle', 'semestrielle', 'annuelle', name='frequence_planning'), nullable=False),
    sa.Column('date_derniere', sa.Date(), nullable=True),
    sa.Column('date_prochaine', sa.Date(), nullable=False),
    sa.Column('statut', sa.Enum('a_jour', 'a_venir', 'retard', name='statut_planning'), nullable=False),
    sa.Column('intervention_id', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['equipement_id'], ['equipements.id'], ),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ),
    sa.ForeignKeyConstraint(['technicien_id'], ['techniciens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plannings')
    op.drop_table('interventions')
    op.drop_table('messages')
    op.drop_table('formations')
    op.drop_index(op.f('ix_equipements_attente_reparation_numero_serie'), table_name='equipements_attente_reparation')
    op.drop_table('equipements_attente_reparation')
    op.drop_table('equipements')
    op.drop_table('conversation_participants')
    op.drop_index(op.f('ix_techniciens_email'), table_name='techniciens')
    op.drop_table('techniciens')
    op.drop_index(op.f('ix_pieces_detachees_reference'), table_name='pieces_detachees')
    op.drop_table('pieces_detachees')
    op.drop_table('evenements')
    op.drop_table('conversations')
    # ### end Alembic commands ###
