"""photo_url technicien

Revision ID: d567127f4981
Revises: 1ed9d106e567
Create Date: 2026-08-14 20:10:45.442831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd567127f4981'
down_revision: Union[str, None] = '1ed9d106e567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('techniciens', sa.Column('photo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('techniciens', 'photo_url')
    # ### end Alembic commands ###
