"""workflow intervention: devis, pieces_necessaires, intervention_documents

Revision ID: f083e97f6e53
Revises: b9361b4e91f8
Create Date: 2026-08-09 15:32:05.534405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f083e97f6e53'
down_revision: Union[str, None] = 'b9361b4e91f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intervention_id', sa.String(length=20), nullable=False),
    sa.Column('montant_pieces', sa.Float(), nullable=False),
    sa.Column('montant_main_oeuvre', sa.Float(), nullable=False),
    sa.Column('montant_total', sa.Float(), nullable=False),
    sa.Column('statut', sa.Enum('brouillon', 'envoye', 'accepte', 'refuse', name='statut_devis'), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('date_decision_client', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_id'], ['techniciens.id'], ),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intervention_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intervention_id', sa.String(length=20), nullable=False),
    # 'bon_restitution' ajouté rétroactivement à cette définition le 2026-09-24 (migration
    # Postgres/Supabase) — valeur Python ajoutée bien plus tard (voir e500f49432a4) mais jamais
    # reflétée en DDL sur cet enum ; sans impact sur SQLite (déjà appliqué, VARCHAR sans
    # contrainte), nécessaire sur Postgres où `type_document` est un vrai type ENUM natif.
    sa.Column('type_document', sa.Enum('diagnostic', 'devis', 'rapport_final', 'bon_restitution', name='type_document'), nullable=False),
    sa.Column('chemin_pdf', sa.String(length=500), nullable=False),
    sa.Column('genere_le', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('genere_par_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genere_par_id'], ['techniciens.id'], ),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pieces_necessaires',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intervention_id', sa.String(length=20), nullable=False),
    sa.Column('piece_detachee_id', sa.Integer(), nullable=False),
    sa.Column('quantite_necessaire', sa.Integer(), nullable=False),
    sa.Column('ajoute_par_id', sa.Integer(), nullable=False),
    sa.Column('date_ajout', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ajoute_par_id'], ['techniciens.id'], ),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['piece_detachee_id'], ['pieces_detachees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # `sa.Enum(...).create(...)` explicite avant chaque `add_column` (ajouté le 2026-09-25,
    # bug trouvé au premier déploiement réel sur Supabase) : contrairement à `op.create_table`,
    # `op.add_column` n'émet PAS automatiquement le `CREATE TYPE` d'un enum Postgres inline —
    # sans ça, l'`ALTER TABLE ... ADD COLUMN` échoue avec `type "lieu_reparation" does not
    # exist`. Sans effet sur SQLite (`Enum.create()` y est un no-op, pas de vrai type). Voir
    # SUIVI_PROJET.md.
    lieu_reparation_enum = sa.Enum('sur_place', 'atelier', name='lieu_reparation')
    lieu_reparation_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('interventions', sa.Column('lieu_reparation', lieu_reparation_enum, nullable=True))
    op.add_column('interventions', sa.Column('description_panne', sa.Text(), nullable=True))
    # server_default explicite : NOT NULL sans défaut échouerait sur SQLite si la table
    # contient déjà des lignes (backfill requis). `default=` côté modèle SQLAlchemy est
    # ORM-only, pas vu par le ALTER TABLE — il faut le server_default ici.
    statut_workflow_enum = sa.Enum(
        'appel_recu', 'diagnostic_en_cours', 'diagnostic_termine', 'devis_en_preparation', 'devis_envoye',
        'devis_accepte', 'devis_refuse', 'travail_en_cours', 'termine', 'annulee', name='statut_workflow',
    )
    statut_workflow_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'interventions',
        sa.Column('statut_workflow', statut_workflow_enum, server_default='appel_recu', nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interventions', 'statut_workflow')
    op.drop_column('interventions', 'description_panne')
    op.drop_column('interventions', 'lieu_reparation')
    op.drop_table('pieces_necessaires')
    op.drop_table('intervention_documents')
    op.drop_table('devis')
    # ### end Alembic commands ###
